
services:
  iam-service:
    build:
      context: .
      dockerfile: apps/iam-service/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./apps/iam-service/.env
    volumes:
      - ./apps/iam-service/jwt-private.pem:/app/jwt-private.pem
      - ./apps/iam-service/jwt-public.pem:/app/jwt-public.pem
    depends_on:
      - redis
    networks:
      - microservice-net

  anonymously:
    build:
      context: .
      dockerfile: apps/anonymously/Dockerfile
    ports:
      - "5000:5000" 
    env_file:
      - ./apps/anonymously/.env
    # depends_on:
    #   - redis
    networks:
      - microservice-net

  # 3. Client (Frontend) in Dev Mode
  client:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter client run dev"
    volumes:
      # Mount all source code for hot-reloading
      - ./:/app
      # Use an anonymous volume to "hide" host node_modules
      # This forces the container to use its own modules
      - /app/node_modules
      - /app/apps/client/.next
    ports:
      - "3000:3000"
    env_file:
      - ./apps/client/.env
    networks:
      - microservice-net

  # 4. Redis Database
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass Hello841211
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - microservice-net

# Define the persistent volume for Redis data
volumes:
  redis-data:

# Define the shared network
networks:
  microservice-net:
    driver: bridge